### PR TITLE
Create Security.md

### PR DESCRIPTION
**Pull request by hackit-coder**
Created new file for Security.md documentation.

### CODE REVIEW

**Comment by hackit-coder** [comment]
Anyone?

**Comment by peterschmidt85** [comment]
@hackit-coder It's suggested that we start with an issue. To me, it doesn't seem the template itself solves any specific problem, or does it?

**Comment by hackit-coder** [comment]
No, but the repo will look more organized almost all good repos have a security file. Please think about it ....

**Comment by hackit-coder** [comment]
Sir can you review it

**Comment by SamirPS** [comment]
I think you should create an issue first

**Comment by peterschmidt85** [comment]
I suggest that you focus on something more impactful, I don't see how just having a blank template will help.

**Pull request closed without merging**
