### PR TITLE
Rename Interruptible to spot

### LINKED ISSUE #289: Rename `interruptible` to `spot` (in the CLI and YAML)

### PR DESCRIPTION
**Pull request by dhanush-2501**
Closes #289 

Renamed interruptible to spot

### CODE REVIEW

**Comment by peterschmidt85** [comment]
@dhanush-2501 Hey, thanks for the PR.
Have you tested the change? It seems like you've only renamed the CLI argument, but the property in the YAML file hasn't been updated. It should be changed as well, along with the documentation. If you need any assistance with this, just let me know!

**Comment by dhanush-2501** [comment]
@peterschmidt85  Thanks for the feedback. will work on it.

**Comment by dhanush-2501** [comment]
@peterschmidt85 Can you pls help me to find the file where I need to do the changes?

**Comment by dhanush-2501** [comment]
and also can u tell me the steps to follow to test the changes?

**Comment by dhanush-2501** [comment]
@peterschmidt85 Figured out how to run the tests. I am running the test using "python -m unittest" at test directory

**Pull request closed without merging**
