### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Reckon-11**
Consistent Indentation and Comments:
Organized comments to clarify each section’s purpose, improving readability.

Reduced Redundant Commands:
Consolidated commands in RUN for faster layer creation and reduced image size.

Metadata Labels:
Enhanced maintainability with structured LABEL statements, making it easy to add or modify metadata.

### CODE REVIEW

**Comment by peterschmidt85** [comment]
@Reckon-11 I suggest before submitting a PR, starting with an issue.

**Comment by Reckon-11** [comment]
Thank you for the suggestion! I appreciate your guidance on this process.

I understand that starting with an issue allows for better discussion and planning before making changes.
But the thing is their is no issue in this.i create the
PR for code improvement and some of Image size reduction and Label them so that they can easily modified in future .but I understand your suggestion on this.
Thanks again for your support!

**Comment by peterschmidt85** [comment]
@Reckon-11 I totally understand you too. When the scope of change and reason is clear, we require no issue. When it's not, it's always better to start with an issue. This helps everyone understand the problem, understand its impact and scope, and focus on the problem rather than doing an improvement just for the sake of it.

**Comment by Reckon-11** [comment]
I understand  👍

**Pull request closed without merging**
