### PR TITLE
Update Base Dockerfile

### PR DESCRIPTION
**Pull request by AranavMahalpure**
Conditional SSH Installation:
By using the INSTALL_SSH build argument, SSH installation becomes optional, reducing security risks if SSH isn’t needed.

Automatic Conda Environment Activation:
Set the SHELL to bash and configured the ENTRYPOINT to source .bashrc so that workflow activates on container startup, ensuring Python and CUDA libraries work as expected.

### CODE REVIEW

**Comment by peterschmidt85** [comment]
@AranavMahalpure I suggest before submitting a PR, starting with an issue.

**Comment by AranavMahalpure** [comment]
Thank you for the suggestion! I appreciate your guidance on this process.

I understand that starting with an issue allows for better discussion and planning before making changes. I will create an issue to outline the proposed changes regarding the conditional SSH installation and the automatic activation of the Conda environment. This way, we can gather feedback and ensure that everyone is aligned before moving forward with the PR.

Once the issue is created and discussed, I can proceed with the PR based on the feedback received.

Thanks again for your support!

**Comment by peterschmidt85** [comment]
@AranavMahalpure Thank you.

Creating an issue helps everyone understand the problem, understand its impact and scope, and focus on the problem rather than doing an improvement just for the sake of it.

**Comment by AranavMahalpure** [comment]
I completely agree! Defining an issue helps everyone understand the problem's impact and focus on effective solutions rather than making changes just for the sake of it.

**Comment by AranavMahalpure** [comment]
Thanks for your guidance and support.  It will help me throughout  my Tech Journey.
thanks man.

**Pull request closed without merging**
