### PR TITLE
Fix Cudo non gpu VM creation

### PR DESCRIPTION
**Pull request by Bihan**
Fix for [Bug](https://github.com/dstackai/dstack/issues/1032)

### CODE REVIEW

**Comment by TheBits** [comment]
@Bihan Hi!
I couldn't start any CPU VM. I could not figure out why the `boot_disk_id` error occurred. 🤷
Can you please look at this error?


```
[06:49:38] DEBUG    job(b65ef6)fuzzy-mole-1-0-0: provisioning has started                                                dstack._internal.server.background.tasks.process_submitted_jobs:90
[06:49:42] DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0250 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0276 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
[06:49:43] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0286 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
           DEBUG    Processed request POST http://127.0.0.1:3000/api/project/main/runs/get in 0.060132s                                                     dstack._internal.server.app:175
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0308 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0322 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0331 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
[06:49:44] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0336 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0341 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0344 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0350 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0354 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
[06:49:45] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0357 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0364 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0367 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
           WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0370 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
[06:49:46] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
                    disk with that id already exists')                                                                                                                                     
           DEBUG    job(b65ef6)fuzzy-mole-1-0-0: provisioning failed                                                    dstack._internal.server.background.tasks.process_submitted_jobs:169
           ```

**Comment by Bihan** [comment]
> @Bihan Hi! I couldn't start any CPU VM. I could not figure out why the `boot_disk_id` error occurred. 🤷 Can you please look at this error?
> 
> ```
> [06:49:38] DEBUG    job(b65ef6)fuzzy-mole-1-0-0: provisioning has started                                                dstack._internal.server.background.tasks.process_submitted_jobs:90
> [06:49:42] DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0250 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0276 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
> [06:49:43] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0286 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
>            DEBUG    Processed request POST http://127.0.0.1:3000/api/project/main/runs/get in 0.060132s                                                     dstack._internal.server.app:175
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0308 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0322 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0331 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
> [06:49:44] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0336 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0341 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0344 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0350 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0354 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
> [06:49:45] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0357 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/in-hyderabad-1 for $0.0364 per hour     dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/in-hyderabad-1 failed: BackendError('A  dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-2 for $0.0367 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
>            WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-2 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: trying intel-broadwell in cudo/ca-montreal-1 for $0.0370 per hour      dstack._internal.server.background.tasks.process_submitted_jobs:236
> [06:49:46] WARNING  job(b65ef6)fuzzy-mole-1-0-0: intel-broadwell launch in cudo/ca-montreal-1 failed: BackendError('A   dstack._internal.server.background.tasks.process_submitted_jobs:254
>                     disk with that id already exists')                                                                                                                                     
>            DEBUG    job(b65ef6)fuzzy-mole-1-0-0: provisioning failed                                                    dstack._internal.server.background.tasks.process_submitted_jobs:169
>            ```
> ```

@TheBits The issue is about unique vm_id and boot_disk_id. What happened  1: Location "in-hyderabad-1" failed but is not terminated. 2: Our code requested VM creation with the same vm_id and boot_disk_id but in different location.  3: Cudo raised "...id already exists" error. 

When I terminated the failed VM from the console, our request for VM creation in different location worked.

Solution:
In `create_instance` function I will terminate the VM if status is failed.

**Comment by TheBits** [comment]
> @TheBits The issue is about unique vm_id and boot_disk_id. What happened 1: Location "in-hyderabad-1" failed but is not terminated. 2: Our code requested VM creation with the same vm_id and boot_disk_id but in different location. 3: Cudo raised "...id already exists" error.
> 
> When I terminated the failed VM from the console, our request for VM creation in different location worked.
> 
> Solution: In `create_instance` function I will terminate the VM if status is failed.

@Bihan Thanks! I agree with your solution.

I believed that instance names should be unique inside the region. But in fact, they are unique in the project!

**Comment by r4victor** [comment]
@Bihan, I forget to merge my Cudo fixes right away (#1082) and I now see this PR has some conflicts. It shouldn't be hard to resolve them, but sorry for the inconvenience with the delay.

**Comment by Bihan** [comment]
> @Bihan, I forget to merge my Cudo fixes right away (#1082) and I now see this PR has some conflicts. It shouldn't be hard to resolve them, but sorry for the inconvenience with the delay.

@r4victor No problem. I will resolve the conflicts and push the changes.

**Comment by Bihan** [comment]
@r4victor 
cc @TheBits 
**Issue**
When the first VM fails, the subsequent options throw `BackendError('A disk with that id already exists')` ultimately failing the provisioning.

This happens because the FAILED VM is not terminated before **trying** subsequent options. When the VM is not terminated, there is an “id” conflict. 

What would you recommend?
1.	Name VM in the format <instance.name>_<region> to make it unique in a project.
2.	Terminate VM when  `get_vm(self, project_id, vm_id)` responds  with FAILED state.
3.     Any other solution?

**Comment by TheBits** [comment]
@Bihan Let's try the first option (Name VM with format) as a the simplest option!

**Comment by Bihan** [comment]
> @Bihan Let's try the first option (Name VM with format) as a the simplest option!

@TheBits This solution works. You can test it by 1. Commenting `if offer.region not in ["in-hyderabad-1"]` in [Here](https://github.com/SMTM-Capital/dstack/blob/02604668d4965eea30a3cbee415e9b8cd3f07c75/src/dstack/_internal/core/backends/cudo/compute.py#L50)

2. Get cpu only offers `dstack run . -b cudo`

**Review by TheBits — APPROVED** [review]

**Comment by TheBits** [comment]
Tnaks @Bihan! I have checked the PR and will merge it.

**Pull request merged**
