### PR TITLE
Adding an example of NIM

### PR DESCRIPTION
**Pull request by deep-diver**
Adding an example of NIM

### CODE REVIEW

**Comment by Bihan** [comment]
Hey @deep-diver,

1. I’ve created a sample [README.md](https://github.com/Bihan/dstack/blob/nim_example/examples/deployment/nim/README.md) that follows dstack's structure. Please note that it assumes the reader is already familiar with NIM. Feel free to update it accordingly.
2. I tested the sample configuration with a 24GB GPU, and it worked. Kindly update the GPU requirement to 24GB.
3. Could you also provide the source-code for the development environment (.dstack.yml), task (task.dstack.yml), and service (service.dstack.yml)

Thanks!

**Comment by deep-diver** [comment]
@Bihan cc: @peterschmidt85 

Sorry for delayed response, and thanks for the comments.
- 2. update 48GB to 24GB is done
- 3. provided `service.dstack.yml` since I wrote this for only deployment purpose with service.

for the first point, your README.md assumes the reader is already familiar with NIM like you said. But, I think giving a bit about the background to readers never hurts anything. Actually, I think it is a good thing.

However, if you think this violates dstack's blogging/writing policy, and this MUST be modified accordingly, feel free to adjust the contents.

**Comment by r4victor** [comment]
@deep-diver, @Bihan what's the status of this PR? Should we merge it?

**Comment by Bihan** [comment]
> @deep-diver, @Bihan what's the status of this PR? Should we merge it?

@r4victor I will adjust the content till tomorrow morning and let you know.

**Comment by deep-diver** [comment]
I think this is ready to be merged 
cc: @peterschmidt85

**Pull request merged**
