### PR TITLE
Update oci_image_tools.py

### PR DESCRIPTION
**Pull request by DhruvKadam-git**
1. Error Handling: Add more specific error messages and handle exceptions where necessary.

2. Logging: Improve logging for better traceability.

3. Code Duplication: Reduce code duplication by creating helper functions.

4. Type Hints: Add type hints for better readability and type checking.

### CODE REVIEW

**Comment by peterschmidt85** [comment]
@DhruvKadam-git Is there an issue that PR fixes? Would be great to start with it. Otherwise, the scope is a bit unclear.

**Comment by DhruvKadam-git** [comment]
> @DhruvKadam-git Is there an issue that PR fixes? Would be great to start with it. Otherwise, the scope is a bit unclear.

Issue is not there but I can raise it and it's bit oriented to error handling and logging traceability

**Comment by peterschmidt85** [comment]
> > @DhruvKadam-git Is there an issue that PR fixes? Would be great to start with it. Otherwise, the scope is a bit unclear.
> 
> Issue is not there but I can raise it and it's bit oriented to error handling and logging traceability

Yes, an issue is very important as it provides more details on what the issue is, how to reproduce it, and what its impact is.

**Comment by DhruvKadam-git** [comment]
Ok so I will open issue now

**Comment by DhruvKadam-git** [comment]
I have raised the ticket ,have a look

**Comment by r4victor** [comment]
This PR simply catches and re-raises exceptions, which does not improve error handling. Such PRs are not going to be merged.

**Comment by DhruvKadam-git** [comment]
Ok so I am closing this PR

**Pull request closed without merging**
